# Permalinks
permalink:           pretty

# Setup
title:               Henri's Mind
tagline:             The Jekyll Butler
url:                 http://blog.tremblay.pro
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Henri Tremblay
  url:               https://twitter.com/henri_tremblay
  email:             henri@tremblay.pro

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/henri-tremblay/blog.git

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
