# Dependencies
highlighter:      rouge

# Permalinks
permalink:           pretty

# Setup
title:               Henri's Mind
tagline:             My thoughts on the world and some useful things I learn daily
url:                 http://blog.tremblay.pro
paginate:            5
baseurl:             "/"
analytics_id:        UA-75727912-1

# About/contact
author:
  name:              Henri Tremblay
  url:               https://twitter.com/henri_tremblay
  email:             henri@tremblay.pro

# Do not build vendor pages (https://github.com/jekyll/jekyll/issues/2938)
exclude: [vendor]

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/henri-tremblay/blog.git

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
